plugins:
  rubocop:
    enabled: true
    exclude_patterns:
    - "vendor/"
  eslint:
   	enabled: true
## other configuration excluded from example...
exclude_patterns:
- "tests/"
- "spec/"
- config/
- db/
- dist/
- features/
- helpers/
- middlewares/
- "**/node_modules/"
- script/
- "**/spec/"
- "**/test/"
- "**/tests/"
- Tests/
- "**/vendor/"
- "**/*_test.go"
- "**/*.d.ts"
