sudo: false

language: node_js

node_js:
  - '10'
  services:
    - postgresql

    before_install:
      - psql -c 'create database testAutomart' -U postgres

# branches:
#     only:
#       - develop

after_success: 
  - npm run coverage

  notifications:
    - email: false
