language: node_js
node_js:
    - 10.15.3

before_install:
    - npm i -g 6.9.0

install:
    - npm install

script:
    - npm test

branches:
    only:
        - develop

after_success:
    - coveralls
    - codeclimate-test-reporter
    - codecov --token=186f1c2b-4731-41ee-9784-a1168bdcb62a
